name: TwentyQuestions
version: 1.0
main: io.dogsbean.twentyquestions.Main
commands:
  게임:
    description: 게임 시작 명령어
    usage: /게임 시작
  주제:
    description: 주제 설정 명령어
    usage: /주제 설정 <주제>
  정답:
    description: 정답 설정/추측 명령어
    usage: /정답 <설정/정답>
  질문:
    description: 질문 명령어
    usage: /질문 <질문>
  기회:
    description: 기회 차감 명령어
    usage: /기회 차감
  정답공개:
    description: 정답 공개 명령어
    usage: /정답 공개
  응답:
    description: O/X 답변 명령어
    usage: /응답 <O/X>
  순서양도:
    description: 다른 플레이어에게 순서를 양도합니다
    usage: /<command> [수락|거절]